dia = input ('Que dia você nasceu?')
mes = input ('Em que mês você nasceu?')
ano = input ('E de que ano foi tudo isso?')
print('Então você nasceu no dia', dia, 'do mês de', mes, 'do ano de', ano,'?')
resposta = input ('Resposta:')
print('Ta ficando velho em meu filho...')
