n1 = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(n1))
print('É um número?', n1.isnumeric())
print('É uma alfabético?', n1.isalpha())
print('É alfanumérico?', n1.isalnum())
print('Está tudo em letras maiúsculas?', n1.isupper())
print('Está tudo em letras minusculas?', n1.islower())
print('Está capitalizada?', n1.istitle())
print('É um numero decimal?', n1.isdecimal())
print('Só tem espaços?', n1.isspace())
print('')
print('Pronto. Agora para de me perguntar todas essas coisas!')
